services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - PG_HOST=postgres
      - PG_DATABASE=${POSTGRES_DB}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/app/api
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "-u", "api/src/scheduler.py"]
    depends_on:
      - postgres
    volumes:
      - ./api:/app/api
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

x-resources: &default-resources
  deploy:
    resources:
      limits:
        memory: 2G


volumes:
  pgdata: