services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:///users.db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scraper:/app/scraper
      - ./data:/app/data
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "-u", "scraper/src/scheduler.py"]
    depends_on:
      - postgres
    volumes:
      - ./scraper:/app/scraper
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auctions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
      - ./users.db:/app/users.db
    depends_on:
      - backend
    restart: unless-stopped

x-resources: &default-resources
  deploy:
    resources:
      limits:
        memory: 2G


volumes:
  pgdata: