version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:///users.db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scraper:/app/scraper
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped