version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:///users.db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scraper:/app/scraper
      - ./data:/app/data
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Same image, but runs different command
    command: ["python", "-u", "scraper/src/scheduler.py"]
    depends_on:
      - redis
    volumes:
      - ./scraper:/app/scraper
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
      - ./users.db:/app/users.db
    depends_on:
      - backend
    restart: unless-stopped